{
 "title": "Execution Events",
 "tags": [ "SSIS" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Instance", "query": "mssql" },
   { "name": "ExecutionID", "query": "3856" },
   { "name": "EventType", "label": "Event Type", "query": "All,Errors,Warnings,Memory" }
  ]
 },
 "panels": [
  {
   "title": "General Information",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "\r\nDECLARE @executionID BIGINT = $ExecutionID;\r\n\r\n\r\nselect \r\n\te.project_name,\r\n\te.package_name,\r\n\tenvironment = isnull(e.environment_folder_name, '') + isnull('\\' + e.environment_name,  ''), \r\n\te.status, \r\n\tstart_time = format(e.start_time, 'yyyy-MM-dd HH:mm:ss'),\r\n\tend_time = format(e.end_time, 'yyyy-MM-dd HH:mm:ss'),\r\n\telapsed_time_min = format(datediff(ss, e.start_time, e.end_time) / 60., '#,0.00')\r\nfrom \r\n\t[catalog].executions e \r\nwhere e.execution_id = @executionID"
    }
   ]
  },
  {
   "title": "Events",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "DECLARE @executionId BIGINT = $ExecutionID;\r\n\r\nSELECT COUNT(*) AS metric\r\nFROM   [catalog].event_messages\r\nWHERE  \toperation_id = @executionId"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "DECLARE @executionId BIGINT = $ExecutionID;\r\n\r\nSELECT COUNT(*) AS metric\r\nFROM   [catalog].event_messages\r\nWHERE  operation_id = @executionId\r\nAND    event_name = 'OnError'"
    }
   ]
  },
  {
   "title": "Warnings",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "DECLARE @executionId BIGINT = $ExecutionID;\r\n\r\nSELECT COUNT(*) AS metric\r\nFROM   [catalog].event_messages\r\nWHERE  operation_id = @executionId\r\nAND    event_name = 'OnWarning'"
    }
   ]
  },
  {
   "title": "Memory Warning",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "DECLARE @executionId BIGINT = $ExecutionID;\r\n\r\nSELECT COUNT(*) AS metric\r\nFROM   [catalog].event_messages\r\nWHERE  operation_id = @executionId\r\nAND    event_name = 'OnInformation' \r\nAND    [message] LIKE '%memory allocation%'"
    }
   ]
  },
  {
   "title": "Events",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "DECLARE @executionId BIGINT = $ExecutionID;\r\n\r\nSELECT \r\n\tmessage_time ,\r\n\t[Message],\r\n\tpackage_name [Package],\r\n\tpackage_path [Package Path],\r\n\tsubcomponent_name [Subcomponent],\r\n\texecution_path [Execution Path]\r\nFROM \t[catalog].event_messages\r\nWHERE operation_id = @executionId\r\nAND ( ( '$EventType' = 'All'  )\r\n    OR ( '$EventType' = 'Errors' AND event_name = 'OnError' )\r\n    OR ( '$EventType' = 'Warnings' AND event_name = 'OnWarning' )\r\n    OR ( '$EventType' = 'Memory' AND event_name = 'OnInformation' AND [message] LIKE '%memory allocation%' )\r\n    )\r\n  "
    }
   ]
  }
 ]
}