{
 "title": "Execution Details",
 "tags": [ "SSIS" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Instance", "query": "mssql" },
   { "name": "ExecutionID", "query": "3856" }
  ]
 },
 "panels": [
  {
   "title": "General Information",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "\r\nDECLARE @executionID BIGINT = $ExecutionID;\r\n\r\n\r\nselect \r\n\te.project_name,\r\n\te.package_name,\r\n\tenvironment = isnull(e.environment_folder_name, '') + isnull('\\' + e.environment_name,  ''), \r\n\te.status, \r\n\tstart_time = format(e.start_time, 'yyyy-MM-dd HH:mm:ss'),\r\n\tend_time = format(e.end_time, 'yyyy-MM-dd HH:mm:ss'),\r\n\telapsed_time_min = format(datediff(ss, e.start_time, e.end_time) / 60., '#,0.00')\r\nfrom \r\n\t[catalog].executions e \r\nwhere e.execution_id = @executionID"
    }
   ]
  },
  {
   "title": "Events",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "DECLARE @executionId BIGINT = $ExecutionID;\r\n\r\nSELECT COUNT(*) AS metric\r\nFROM   [catalog].event_messages\r\nWHERE  \toperation_id = @executionId"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "DECLARE @executionId BIGINT = $ExecutionID;\r\n\r\nSELECT COUNT(*) AS metric\r\nFROM   [catalog].event_messages\r\nWHERE  operation_id = @executionId\r\nAND    event_name = 'OnError'"
    }
   ]
  },
  {
   "title": "Warnings",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "DECLARE @executionId BIGINT = $ExecutionID;\r\n\r\nSELECT COUNT(*) AS metric\r\nFROM   [catalog].event_messages\r\nWHERE  operation_id = @executionId\r\nAND    event_name = 'OnWarning'"
    }
   ]
  },
  {
   "title": "Memory Warning",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "DECLARE @executionId BIGINT = $ExecutionID;\r\n\r\nSELECT COUNT(*) AS metric\r\nFROM   [catalog].event_messages\r\nWHERE  operation_id = @executionId\r\nAND    event_name = 'OnInformation' \r\nAND    [message] LIKE '%memory allocation%'"
    }
   ]
  },
  {
   "title": "Executables",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "declare @executionIdFilter bigint = $ExecutionID;\r\n\r\nselect\r\n\tes.statistics_id,\r\n\te.executable_name,\r\n\tREPLACE(es.execution_path, '\\', ' \\' ) execution_path,\r\n\tstart_time = format(es.start_time, 'yyyy-MM-dd HH:mm:ss'),\r\n\tend_time = format(es.end_time, 'yyyy-MM-dd HH:mm:ss'),\r\n\texecution_duration_min = datediff(minute, es.start_time, es.end_time),\r\n\t[status] = es.execution_result\r\nfrom\r\n\t[catalog].[executables] e \r\ninner join\r\n\t[catalog].[executable_statistics] es on e.executable_id = es.executable_id and e.execution_id = es.execution_id\r\nwhere\r\n\tes.execution_id = @executionIdFilter\r\norder by\r\n\tes.start_time"
    }
   ]
  }
 ]
}