{
 "title": "Execution Parameters & Overrides",
 "tags": [ "SSIS" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Instance", "query": "mssql" },
   { "name": "ExecutionID", "query": "381" }
  ]
 },
 "panels": [
  {
   "title": "General Information",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "\r\nDECLARE @executionID BIGINT = $ExecutionID;\r\n\r\n\r\nselect \r\n\te.project_name,\r\n\te.package_name,\r\n\tenvironment = isnull(e.environment_folder_name, '') + isnull('\\' + e.environment_name,  ''), \r\n\te.status, \r\n\tstart_time = format(e.start_time, 'yyyy-MM-dd HH:mm:ss'),\r\n\tend_time = format(e.end_time, 'yyyy-MM-dd HH:mm:ss'),\r\n\telapsed_time_min = format(datediff(ss, e.start_time, e.end_time) / 60., '#,0.00')\r\nfrom \r\n\t[catalog].executions e \r\nwhere e.execution_id = @executionID"
    }
   ]
  },
  {
   "title": "Events",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "DECLARE @executionId BIGINT = $ExecutionID;\r\n\r\nSELECT COUNT(*) AS metric\r\nFROM   [catalog].event_messages\r\nWHERE  \toperation_id = @executionId"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "DECLARE @executionId BIGINT = $ExecutionID;\r\n\r\nSELECT COUNT(*) AS metric\r\nFROM   [catalog].event_messages\r\nWHERE  operation_id = @executionId\r\nAND    event_name = 'OnError'"
    }
   ]
  },
  {
   "title": "Warnings",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "DECLARE @executionId BIGINT = $ExecutionID;\r\n\r\nSELECT COUNT(*) AS metric\r\nFROM   [catalog].event_messages\r\nWHERE  operation_id = @executionId\r\nAND    event_name = 'OnWarning'"
    }
   ]
  },
  {
   "title": "Memory Warning",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "DECLARE @executionId BIGINT = $ExecutionID;\r\n\r\nSELECT COUNT(*) AS metric\r\nFROM   [catalog].event_messages\r\nWHERE  operation_id = @executionId\r\nAND    event_name = 'OnInformation' \r\nAND    [message] LIKE '%memory allocation%'"
    }
   ]
  },
  {
   "title": "Parameters",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "declare @executionId bigint = $ExecutionID;\r\n\r\nselect \r\n\t[Type] = \r\n\t\tcase object_type \r\n\t\t\twhen 20 then 'Project'\r\n\t\t\twhen 30 then 'Package'\r\n\t\t\twhen 50 then 'System'\r\n\t\t\telse 'Unknown'\r\n\t\tend,\r\n\tparameter_name [Parameter],\r\n\tparameter_data_type [Data Type],\r\n\t[Value] = cast(parameter_value as nvarchar(max)),\r\n\tvalue_set [Set],\r\n\truntime_override [Override]\r\nfrom \r\n\t[catalog].[execution_parameter_values] \r\nwhere \r\n\t[execution_id] = @executionId\r\nORDER BY [Type] DESC"
    }
   ]
  },
  {
   "title": "Property Overrides",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "declare @executionId bigint = $ExecutionID;\r\n\r\nselect \r\n\tproperty_path [Path],\r\n\t[Value] = cast(property_value as nvarchar(max))\r\nfrom \r\n\t[catalog].[execution_property_override_values] \r\nwhere \r\n\t[execution_id] = @executionId"
    }
   ]
  }
 ]
}