{
 "title": "SSIS Dashboard",
 "tags": [ "SSIS" ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Instance", "query": "mssql" },
   { "name": "Folder" },
   { "name": "Project" },
   { "name": "Package" },
   {
    "name": "Status",
    "query": "Created,Running,Cancelled,Failed,Pending,Ended,Succeeded,Stopping,Completed"
   }
  ]
 },
 "panels": [
  {
   "title": "Executions",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "select\r\n  COUNT(*)  AS metric\r\nfrom SSISDB.[catalog].executions e\r\nWHERE e.start_time >=  CONVERT( DATETIMEOFFSET, $__timeFrom(), 0 ) \r\nAND   e.start_time <   CONVERT( DATETIMEOFFSET, $__timeTo(), 0 ) "
    }
   ]
  },
  {
   "title": "Active",
   "type": "singlestat",
   "description": "Includes Created, Running, Pending & Stopping packages",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "select\r\n\tCOALESCE( sum(case when e.[status] IN ( 1,2,5,8 ) then 1 else 0 end), 0 ) AS metric\r\nfrom [catalog].executions e\r\nWHERE e.start_time >=  CONVERT( DATETIMEOFFSET, $__timeFrom(), 0 ) \r\nAND   e.start_time <   CONVERT( DATETIMEOFFSET, $__timeTo(), 0 ) \r\n\r\n"
    }
   ]
  },
  {
   "title": "Cancelled",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "select\r\n\tCOALESCE( sum(case when e.[status] = 3 then 1 else 0 end), 0 ) AS cancelled_packages\r\nfrom [catalog].executions e\r\nWHERE e.start_time >=  CONVERT( DATETIMEOFFSET, $__timeFrom(), 0 ) \r\nAND   e.start_time <   CONVERT( DATETIMEOFFSET, $__timeTo(), 0 ) \r\n\r\n"
    }
   ]
  },
  {
   "title": "Succeeded",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "select\r\n\t\r\n\tCOALESCE( sum(case when e.[status] = 7 then 1 else 0 end), 0 ) AS succeeded_packages\r\nfrom [catalog].executions e\r\nWHERE e.start_time >=  CONVERT( DATETIMEOFFSET, $__timeFrom(), 0 ) \r\nAND   e.start_time <   CONVERT( DATETIMEOFFSET, $__timeTo(), 0 ) \r\n\r\n"
    }
   ]
  },
  {
   "title": "Failed",
   "type": "singlestat",
   "description": "Includes Failed, Ended & Completed packages",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "select\r\n\t\r\n\tCOALESCE( sum(case when e.[status] IN ( 4,6,9 ) then 1 else 0 end), 0 ) AS failed_packages\r\nfrom [catalog].executions e\r\nWHERE e.start_time >=  CONVERT( DATETIMEOFFSET, $__timeFrom(), 0 ) \r\nAND   e.start_time <   CONVERT( DATETIMEOFFSET, $__timeTo(), 0 ) \r\n\r\n"
    }
   ]
  },
  {
   "title": "Executions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "DECLARE @folderNamePattern NVARCHAR(100) = '%$Folder%';\r\nDECLARE @projectNamePattern NVARCHAR(100) = '%$Project%';\r\nDECLARE @packageNamePattern NVARCHAR(100) = '%$Package%';\r\n\r\nselect $__timeGroup(e.start_time, '1h', 0 ) AS [time],\r\n COALESCE( sum(case when e.[status] IN ( 1,2,5,8 ) then 1 else 0 end), 0 ) AS active_packages ,\r\n\tCOALESCE( sum(case when e.[status] = 3 then 1 else 0 end), 0 ) AS cancelled_packages,\r\n\tCOALESCE( sum(case when e.[status] = 7 then 1 else 0 end), 0 ) AS succeeded_packages,\r\n\tCOALESCE( sum(case when e.[status] IN ( 4,6,9 ) then 1 else 0 end), 0 ) AS failed_packages\r\nfrom [catalog].executions e\r\nWHERE e.start_time >=  CONVERT( DATETIMEOFFSET, $__timeFrom(), 0 ) \r\nAND   e.start_time <   CONVERT( DATETIMEOFFSET, $__timeTo(), 0 ) \r\nAND   e.folder_name like @folderNamePattern\r\nAND   e.project_name like @projectNamePattern\r\nAND   e.package_name like @packageNamePattern\r\nGROUP BY  $__timeGroup(e.start_time, '1h', 0)\r\nORDER BY $__timeGroup(e.start_time, '1h', 0)"
    }
   ]
  },
  {
   "title": "Executions",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "\r\nDECLARE @folderNamePattern NVARCHAR(100) = '%$Folder%';\r\nDECLARE @projectNamePattern NVARCHAR(100) = '%$Project%';\r\nDECLARE @packageNamePattern NVARCHAR(100) = '%$Package%';\r\n\r\n\r\nwith cteWE as\r\n(\r\n\tselect \r\n\t\toperation_id, event_name, event_count = count(*)\r\n\tfrom \r\n\t\t[catalog].event_messages \r\n\twhere\r\n\t\tevent_name in ('OnError', 'OnWarning')\r\n\tgroup by\r\n\t\toperation_id, event_name\r\n),\r\ncteKPI as\r\n(\r\n\tselect\r\n\t\toperation_id,\r\n\t\t[errors] = OnError,\r\n\t\twarnings = OnWarning\r\n\tfrom\r\n\t\tcteWE\r\n\tpivot\r\n\t\t(\r\n\t\t\tsum(event_count) for event_name in (OnError, OnWarning)\r\n\t\t) p\r\n),\r\ncteLoglevel as\r\n(\r\n\tselect\r\n\t\texecution_id,\r\n\t\tcast(parameter_value as int) as logging_level\r\n\tfrom\r\n\t\t[catalog].[execution_parameter_values]\r\n\twhere\r\n\t\tparameter_name = 'LOGGING_LEVEL'\r\n)\r\nselect \r\n\te.execution_id, \r\n\te.project_name,\r\n\te.package_name,\r\n\te.project_lsn,\r\n\tenvironment = isnull(e.environment_folder_name, '') + isnull('\\' + e.environment_name,  ''), \r\n\te.status, \r\n\tstart_time = format(e.start_time, 'yyyy-MM-dd HH:mm:ss'),\r\n\tend_time = format(e.end_time, 'yyyy-MM-dd HH:mm:ss'),\r\n\telapsed_time_min = format(datediff(ss, e.start_time, e.end_time) / 60., '#,0.00'),\r\n\tk.warnings,\r\n\tk.errors,\r\n\tl.logging_level\r\nfrom \r\n\t[catalog].executions e \r\nleft outer join\r\n\tcteKPI k on e.execution_id = k.operation_id\r\nleft outer join\r\n\tcteLoglevel l on e.execution_id = l.execution_id\r\nwhere e.folder_name like @folderNamePattern\r\nand   e.project_name like @projectNamePattern\r\nand   e.package_name like @packageNamePattern\r\nAND e.start_time >=  CONVERT( DATETIMEOFFSET, $__timeFrom(), 0 ) \r\nAND   e.start_time <   CONVERT( DATETIMEOFFSET, $__timeTo(), 0 ) \r\nAND CASE e.status \r\n      WHEN 1 THEN 'Created'\r\n      WHEN 2 THEN 'Running'\r\n      WHEN 3 THEN 'Cancelled'\r\n      WHEN 4 THEN 'Failed'\r\n      WHEN 5 THEN 'Pending'\r\n      WHEN 6 THEN 'Ended'\r\n      WHEN 7 THEN 'Succeeded'\r\n      WHEN 8 THEN 'Stopping'\r\n      WHEN 9 THEN 'Completed'\r\n    END\r\nIN ($Status)\r\n\r\norder by \r\n\te.execution_id desc\r\noption\r\n\t(recompile)"
    }
   ]
  }
 ]
}